import Link from "next/link";
import { StatusBadge } from "@/components/ui/status-badge";
import { date, money, recordId } from "@/lib/format";

type Passport = { equipment: { id: unknown; name: string; inventoryNumber: string; serialNumber?: string; price?: number; status: string; condition: string; photoFileId?: string; acquisitionDate?: string }; movements: Array<Record<string, unknown>>; repairs: Array<Record<string, unknown>>; audits: Array<Record<string, unknown>>; files: Array<Record<string, unknown>> };
export function EquipmentPassport({ data }: { data: Passport }) {
  const item = data.equipment;
  return <section className="passport equipment-passport"><div className="passport-photo">{item.photoFileId ? <img src={`/api/files/${encodeURIComponent(item.photoFileId)}/full`} alt={`Фото: ${item.name}`}/> : <p>Фотографія відсутня</p>}</div><div className="passport-title"><p className="eyebrow">ІНВЕНТАРНИЙ ПАСПОРТ</p><h1>{item.name}</h1><StatusBadge status={item.condition}/><StatusBadge status={item.status}/><code>{item.inventoryNumber}</code></div><div className="technical-strip"><span>Серійний номер <b>{item.serialNumber || "—"}</b></span><span>Вартість <b>{money.format(Number(item.price ?? 0))}</b></span><span>Надходження <b>{item.acquisitionDate ? date.format(new Date(item.acquisitionDate)) : "—"}</b></span><span>Рухів <b>{data.movements.length}</b></span></div><section><h2>Ланцюг відповідальності</h2><div className="timeline">{data.movements.map((entry, index) => <p key={index}>{String(entry.movementType)} · {String(entry.movementDate)}</p>)}{data.movements.length === 0 && <p>Історія ще не сформована.</p>}</div></section><section><h2>Файли</h2><div className="compact-list">{data.files.map((file) => <div key={recordId(file.id)}><strong>{String(file.name)}</strong><span>{String(file.mimeType)}</span><Link href={`/api/files/${encodeURIComponent(recordId(file.id))}/full`}>Відкрити</Link></div>)}{data.files.length === 0 && <p>Файли не додано.</p>}</div></section></section>;
}
