"use client";

import { useActionState } from "react";
import { createEquipmentAction, type EquipmentActionState } from "@/server/actions/equipment";
import { FileUpload } from "@/components/files/file-upload";

const initial: EquipmentActionState = {};
export function EquipmentForm({ categories, rooms, users }: { categories: Array<{ id: unknown; name: string }>; rooms: Array<{ id: unknown; number?: string; name?: string }>; users: Array<{ id: unknown; fullName?: string }> }) {
  const [state, action, pending] = useActionState(createEquipmentAction, initial);
  return <form noValidate action={action} className="passport-form"><div className="form-grid"><label>Назва<input name="name" aria-invalid={Boolean(state.fieldErrors?.name)} /></label><label>Інвентарний номер<input name="inventoryNumber" aria-invalid={Boolean(state.fieldErrors?.inventoryNumber)} /></label><label>Категорія<select name="categoryId" defaultValue=""><option value="" disabled>Оберіть категорію</option>{categories.map((entry) => <option key={String(entry.id)} value={String(entry.id)}>{entry.name}</option>)}</select></label><label>Приміщення<select name="roomId" defaultValue=""><option value="" disabled>Оберіть приміщення</option>{rooms.map((entry) => <option key={String(entry.id)} value={String(entry.id)}>{entry.number} {entry.name}</option>)}</select></label><label>Відповідальна особа<select name="responsibleId" defaultValue=""><option value="" disabled>Оберіть особу</option>{users.map((entry) => <option key={String(entry.id)} value={String(entry.id)}>{entry.fullName}</option>)}</select></label><label>Стан<select name="condition" defaultValue="good"><option value="new">Нове</option><option value="good">Справне</option><option value="satisfactory">Задовільне</option><option value="needs_repair">Потребує ремонту</option><option value="damaged">Пошкоджене</option><option value="unusable">Непридатне</option></select></label><label>Серійний номер<input name="serialNumber" /></label><label>Виробник<input name="manufacturer" /></label><label>Модель<input name="model" /></label><label>Вартість<input name="price" inputMode="decimal" defaultValue="0" /></label><label>Дата надходження<input name="acquisitionDate" type="date" /></label><FileUpload /></div>{state.formError && <p className="form-error">{state.formError}</p>}{Object.values(state.fieldErrors ?? {}).map((error) => <p className="field-error" key={error}>{error}</p>)}<button className="primary-button" type="submit" disabled={pending}>{pending ? "Реєструємо…" : "Зареєструвати обладнання"}</button></form>;
}
