"use client";

import { useActionState } from "react";
import { createAuditAction, createRepairAction, createTransferRequestAction, createWriteoffAction, type WorkflowActionState } from "@/server/actions/workflows";

const initial: WorkflowActionState = {};
type EquipmentOption = { id: unknown; name: string; inventoryNumber: string; currentRoomId: string };
type RoomOption = { id: unknown; number: string };
const submit = (pending: boolean, text: string) => <button className="primary-button" type="submit" disabled={pending}>{pending ? "Зберігаємо…" : text}</button>;
const errors = (state: WorkflowActionState) => <>{state.formError && <p className="form-error">{state.formError}</p>}{Object.values(state.fieldErrors ?? {}).map((error) => <p className="field-error" key={error}>{error}</p>)}{state.success && <p className="success-note">{state.success}</p>}</>;
export function TransferRequestForm({ equipment, rooms }: { equipment: EquipmentOption[]; rooms: RoomOption[] }) { const [state, action, pending] = useActionState(createTransferRequestAction, initial); return <form action={action} noValidate className="passport-form"><div className="form-grid"><label>Обладнання<select name="equipmentId" defaultValue=""><option value="" disabled>Оберіть обладнання</option>{equipment.map((item) => <option key={String(item.id)} value={String(item.id)}>{item.name} · {item.inventoryNumber}</option>)}</select></label><label>Звідки<select name="fromRoomId" defaultValue=""><option value="" disabled>Оберіть приміщення</option>{rooms.map((room) => <option key={String(room.id)} value={String(room.id)}>{room.number}</option>)}</select></label><label>Куди<select name="toRoomId" defaultValue=""><option value="" disabled>Оберіть приміщення</option>{rooms.map((room) => <option key={String(room.id)} value={String(room.id)}>{room.number}</option>)}</select></label><label>Причина<textarea name="reason" rows={3}/></label></div>{errors(state)}{submit(pending,"Подати заявку")}</form>; }
export function RepairForm({ equipment, rooms }: { equipment: EquipmentOption[]; rooms: RoomOption[] }) { const [state, action, pending] = useActionState(createRepairAction, initial); return <form action={action} noValidate className="passport-form"><div className="form-grid"><label>Обладнання<select name="equipmentId" defaultValue=""><option value="" disabled>Оберіть обладнання</option>{equipment.map((item) => <option key={String(item.id)} value={String(item.id)}>{item.name}</option>)}</select></label><label>Приміщення<select name="roomId" defaultValue=""><option value="" disabled>Оберіть приміщення</option>{rooms.map((room) => <option key={String(room.id)} value={String(room.id)}>{room.number}</option>)}</select></label><label>Серйозність<select name="severity" defaultValue="medium"><option value="low">Низька</option><option value="medium">Середня</option><option value="high">Висока</option></select></label><label>Опис несправності<textarea name="issueDescription" rows={3}/></label></div>{errors(state)}{submit(pending,"Повідомити про несправність")}</form>; }
export function AuditForm({ rooms }: { rooms: RoomOption[] }) { const [state, action, pending] = useActionState(createAuditAction, initial); return <form action={action} noValidate className="passport-form"><div className="form-grid"><label>Назва<input name="title" /></label><label>Приміщення<select name="roomId" defaultValue=""><option value="" disabled>Оберіть приміщення</option>{rooms.map((room) => <option key={String(room.id)} value={String(room.id)}>{room.number}</option>)}</select></label><label>Запланована дата<input name="plannedDate" type="date" /></label></div>{errors(state)}{submit(pending,"Створити аудит")}</form>; }
export function WriteoffForm({ equipment }: { equipment: EquipmentOption[] }) { const [state, action, pending] = useActionState(createWriteoffAction, initial); return <form action={action} noValidate className="passport-form"><div className="form-grid"><label>Обладнання<select name="equipmentId" defaultValue=""><option value="" disabled>Оберіть обладнання</option>{equipment.map((item) => <option key={String(item.id)} value={String(item.id)}>{item.name} · {item.inventoryNumber}</option>)}</select></label><label>Причина<textarea name="reason" rows={3}/></label></div>{errors(state)}{submit(pending,"Подати на списання")}</form>; }
